PLhery/node-twitter-api-v2

- src/client.subclient.ts
- src/v2/TweetPaginator.ts
- src/v2/client.v2.read.ts
- src/v2/types.v2.ts
Slightly refactor some things from @alkihis PR
- I don't thing there's a need for PaginatorParams (instead of just the search params)
- [style] use more decomposition, add brackets to if
- don't mutate the option object passed as parameter
- don't set the maxValue to 10, it's supposed to already be 10 and can change in the future (why would we force it)
- what = query, query/option=queryParams (otherwise it can be a bit confusing reading Twitter's doc)
- Add number as a possible queryParam value, set maxResult as number or string
> chore(tweetPaginator): minor changes to v2.search and tweetPaginator

- .github/workflows/CI.yml
- src/test/index.ts
- src/test/utils.ts
- test/auth.test.ts
- test/stream.test.ts
Use process.env instead of leveraging only on the .env file
Runs npm test in the CI for node 14 and 15. One test fails on node 12, it will be added later.
> chore(CI): Run tests in github workflow, leverage env variables

- src/types/v2/tweet.definition.v2.ts
- src/types/v2/tweet.v2.types.ts
Fix typings for media.fields where non public metrics were missing.
Fix missing `url` prop in `MediaObjectV2`.
> Fix typings for medias V2

- package.json
- src/types/v2/tweet.definition.v2.ts
Added 4 optional parameters to TweetEntityUrlV2
```yaml
title?: string;
description?: string;
status?: string;
images?: {
url: string;
width: number;
height: number;
}
```
These parameters are returned along with others when the URL contains valid OG tags. These properties show up in URL preview cards on Twitter UI. For reference, check "urls" in "entities" in the description column for the field value "entities" in this [Twiter API Documentaion](https://developer.twitter.com/en/docs/twitter-api/data-dictionary/object-model/tweet). Note that `image` parameter is not shown in the example but can be seen in the actual response from the API.
> Added 4 optional paramerters in TweetEntityUrlV2

- doc/paginators.md
- src/paginators/tweet.paginator.v2.ts
Add .meta and .includes in v2 paginators (and document it :D).
This answers this issue (https://github.com/PLhery/node-twitter-api-v2/issues/35) and make this PR (https://github.com/PLhery/node-twitter-api-v2/pull/45) obsolete (sorry, I haven't seen it before making this branch!).
> feat: Add .meta and .includes access for v2 paginators

- src/paginators/tweet.paginator.v2.ts
When using `fetchLast` on `twitterClient.v2.userTimeline`, it throws the following error.
```
(node:64827) UnhandledPromiseRejectionWarning: TypeError: result.data is not iterable (cannot read property undefined)
at TweetUserTimelineV2Paginator.refreshInstanceFromResult (XXX/node_modules/twitter-api-v2/dist/paginators/tweet.paginator.v2.js:14:33)
at TweetUserTimelineV2Paginator.fetchLast (XXX/node_modules/twitter-api-v2/dist/paginators/TwitterPaginator.js:69:24)
at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:64827) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a …
```
> Fixed handling of empy results in TweetTimelineV2Paginator

- doc/v1.md
- package-lock.json
- package.json
- src/paginators/TwitterPaginator.ts
- src/paginators/dm.paginator.v1.ts
- src/types/v1/dm.v1.types.ts
- src/types/v1/index.ts
- src/types/v1/tweet.v1.types.ts
- src/v1/client.v1.ts
- src/v1/client.v1.write.ts
- test/dm.v1.test.ts
Provide wrappers and paginators to nearly every public DM endpoints (in 1.1 API):
- Send, get, list and delete DM events
- Send, get, list, update and delete welcome DMs
- Create, get, list and delete welcome DM rules (+ helper to combine list+delete+create)
- Mark a DM as read
- Indicate typing in a DM 1-to-1 conversation
With appropriate documentation + test suite :)
*Note*: Test suite is disabled by default, as it requires a user-defined sender ID and an application that supports direct messages auth level. To enable test suite, define env variable `TARGET_DM_USER_ID`.
> API v1.1 Direct Message endpoint wrappers

- package-lock.json
- src/client/readonly.ts
- src/types/auth.types.ts
- force_login: Forces the user to enter their credentials to ensure the correct users account is authorized.
- screen_name: Prefills the username input box of the OAuth login screen with the given value.
> Add oauth/authenticate parameters

- package-lock.json
- src/client-mixins/oauth1.helper.ts
- src/stream/TweetStreamEventCombiner.ts
- src/test/utils.ts
- src/types/v1/tweet.v1.types.ts
- src/v1/client.v1.write.ts
- src/v1/media-helpers.v1.ts
- test/media-upload.test.ts
- tsconfig.json
Fixes https://github.com/PLhery/node-twitter-api-v2/issues/56
If we don't explicitely write `import * as fs from 'fs'` instead of  `import fs from 'fs'`, our typescript definition files won't have this form neither.
Because some projects may have allowSyntheticDefaultImport=false, let's set it to false to improve compatibility
> chore: set allowSyntheticDefaultImport to false to improve compatibility

- src/types/v2/tweet.v2.types.ts
via issue #58 
Added missing `non_public_metrics`, `promoted_metrics` and `organic_metrics` fields to `tweet.fields`
> Added non_public_metrics, promoted_metrics and organic_metrics to tweet.fields

- src/paginators/TwitterPaginator.ts
- src/paginators/tweet.paginator.v1.ts
- src/paginators/tweet.paginator.v2.ts
- src/paginators/user.paginator.v2.ts
Fix incorrect max results in paginators when max results is explicit in query params.
+ Set default parameter value `count` to `Infinity` for `.fetchLast` method in paginators.
Addresses #74.
> fix: Fix incorrect max results in paginators

- package-lock.json
- src/types/v2/tweet.definition.v2.ts
- src/types/v2/tweet.v2.types.ts
- src/v2/client.v2.write.ts
- test/tweet.v2.test.ts
Adds the v2 API endpoint for posting a tweet
Documentation followed at [POST Tweet](https://developer.twitter.com/en/docs/twitter-api/tweets/manage-tweets/api-reference/post-tweets)
PS: This project is really awesome, and valuable! Thanks for putting in the effort
> feat: add v2 post single tweet

- src/types/v2/tweet.v2.types.ts
- src/v2/client.v2.write.ts
Add method to delete tweet based on API doc at [Delete tweet](https://developer.twitter.com/en/docs/twitter-api/tweets/manage-tweets/api-reference/delete-tweets-id)
PS: I'll like to add a test case for this after [Post tweet ](https://github.com/PLhery/node-twitter-api-v2/pull/110)  is merged, if a test is required
> feat: add v2 delete tweet

- src/v2/client.v2.read.ts
I have changed `userMutingUsers` to explicitly specify the `userId` just like `userBlockingUsers`.  
It avoids the errors in calling v1.1 API internally when users use the Essential Level of [Twitter API V2 Access Levels](https://developer.twitter.com/en/docs/twitter-api/getting-started/about-twitter-api#v2-access-level).  
This PR contains a breaking change, and if users have already used this API without specifying `userId`, the change will be required.
> Explicitly specify `userId` on `userMutingUsers`

- package.json
- src/types/v2/tweet.definition.v2.ts
The PR #42 introduced the optional property `images` to the `TweetEntityUrlV2`.  
Unfortunately, it assumed that the `images` property is only a single object.  
During some testing, the Twitter API V2 always returned an array of objects instead of a single object.  
The [official documentation](https://developer.twitter.com/en/docs/twitter-api/data-dictionary/object-model/tweet) also shows that `images` is an array of objects.
```
"entities": {
"urls": [
{
"images": [
{
"url": "https://pbs.twimg.com/news_img/1261301555787108354/9yR4UVsa?format=png&name=orig",
"width": 100,
"height": 100
},
{
"url": "https://pbs.twimg.com/news_img/1261301555787108354/9yR4UVsa?format=png&name=150x150",
"width": 100,
"height": 100
}
],
}
]
},
```
This PR changes the type of `images` to an array of a new …
> Fix wrong type for optional parameter images in TweetEntityUrlV2

- doc/auth.md
> Typo fixed `oauth_verified` -> `oauth_verifier`

- doc/v2.md
We can either provide a valid example or remove this "tweet.fields" one because this method doesn't return tweets.
> The options example for v2.me() doesn't make sense

- doc/v2.md
- src/paginators/user.paginator.v2.ts
- src/types/v2/tweet.v2.types.ts
- src/types/v2/user.v2.types.ts
- src/v2/client.v2.read.ts
- Add (optional) paginator support for `tweets/:id/liking_users` and `tweets/:id/retweeted_by` in v2 API. #165
> feat: Pagination for tweet liked by / tweet retweeted by

- src/client-mixins/oauth1.helper.ts
- src/client-mixins/request-param.helper.ts
- src/client/readonly.ts
Due to a misusage of `.searchParams` of `URL` object, that don't correctly encode all URI components, scope was generated incorrectly.
Removed every usage of `.searchParams` in the project to avoid other errors.
Addresses #184
> fix: Fix OAuth 2 scope encoding

- doc/v1.md
- doc/v2.md
HTTP wrappers (.get, .post...) doc has been moved from basics to its own section ; though the links to it were not updated.
> chore(doc): fix the links to http wrappers doc

- doc/v1.md
- src/client-mixins/request-handler.helper.ts
- src/client-mixins/request-maker.mixin.ts
- src/types/request-maker.mixin.types.ts
- src/v1/client.v1.ts
Made small tweaks to allow image download from `ton.twitter.com`, which needs OAuth 1.0a signature to download DM images
Implement a new getter, `.downloadDmImage()`, available on `.v1` (with DM rights).
> Feat: DM image getter

- doc/auth.md
For the example request down below, we need to set async.
> doc: fix missing async on OAuth2 login

- src/paginators/tweet.paginator.v2.ts
> fix: Auto-convert start_time to a since_id when until ID is required

- src/client-mixins/request-maker.mixin.ts
- src/types/plugins/client.plugins.types.ts
With an update of `@twitter-api-v2/plugin-rate-limit`, addresses #226.
> feat: Support response error hooks in plugins

- doc/v2.md
- src/paginators/tweet.paginator.v1.ts
- src/paginators/tweet.paginator.v2.ts
- src/types/auth.types.ts
- src/types/v2/spaces.v2.types.ts
- src/types/v2/tweet.v2.types.ts
- src/v2/client.v2.read.ts
- src/v2/client.v2.write.ts
- feat: New spaces features: topic_ids and ended_at on space object, /spaces/:id/buyers endpoint #237
- feat: New bookmarks API #237
- feat: New Quoted tweets endpoint #237 
- feat: Allow `v2.search` to be used without query parameter #252
- fix: Usertimeline v1 endpoint .done property value is false #238
> feat: 2022 march Twitter API v2 update

- src/v1/client.v1.write.ts
- src/v2/client.v2.write.ts
Adds a `quote` method to the `TwitterApiv1ReadWrite` class that takes the same parameters as `tweet`, in addition to `quoting_status_id: string`. Calls `v1.singleTweet` to get the username of the author of the quoted tweet, uses that to generate the appropriate QT url and appends the url to the status. Then calls `.tweet` as normal.
Passes all tests.
> add .quote method to v1ReadWrite

- src/types/v2/tweet.definition.v2.ts
TweetEntityMentionV2 **interface** is missing the `id` prop.
> fix: missing id prop of TweetEntityMentionV2

- src/types/v1/tweet.v1.types.ts
Reference: https://developer.twitter.com/en/docs/twitter-api/v1/tweets/post-and-engage/api-reference/post-statuses-update
From the docs:
> If a `place_id` is passed into the status update, then that place will be attached to the status. If no `place_id` was explicitly provided, but `latitude` and `longitude` are, the API attempts to implicitly provide a place by calling `geo/reverse_geocode`.
> Add place_id to SendTweetV1Params

- src/types/v2/tweet.definition.v2.ts
- src/types/v2/tweet.v2.types.ts
- test/tweet.v2.test.ts
This adds typings for the `media.fields` entry `"variants"` that is missing, and also adds a new `MediaVariantsV2` type to the `MediaOvjectV2` object.  I also added a test to show that such a call works as expected.
```
✔ .tweetWithMedia - Get a tweet with media variants (200ms)
```
> Add media variants typings.

- doc/v2.md
Hi there!
Thanks for this amazing project 🙌
I have been reading the docs and, at first, I wasn't able to find how to get a single tweet by DM.
After some research I found that v1 docs have the "**Get a** Single Tweet" entry (https://github.com/PLhery/node-twitter-api-v2/blob/master/doc/v1.md#Getasingletweet) but the v2 don't. I think adding this might be helpful as "Single tweet" can be confusing (it could mean "Tweet a _single tweet_" or "Get a _single tweet_")
I usually use `ctrl+f` to find in docs and "Single tweet" is not something I would type. I think "Retrieve a tweet" or "Get a tweet" are more descriptive alternatives.
> docs: make "single tweet" more descriptive

- doc/v1.md
- src/paginators/followers.paginator.v1.ts
- src/paginators/friends.paginator.v1.ts
- src/paginators/index.ts
- src/types/v1/user.v1.types.ts
- src/v1/client.v1.read.ts
Code to get the Ids of friends and followers of the specified user has been written.
Wrappers for the following endpoints have been written:
- https://developer.twitter.com/en/docs/twitter-api/v1/accounts-and-users/follow-search-get-users/api-reference/get-friends-ids
- https://developer.twitter.com/en/docs/twitter-api/v1/accounts-and-users/follow-search-get-users/api-reference/get-followers-ids
> feat: get friends/followers ids V1

- doc/v1.md
- src/paginators/followers.paginator.v1.ts
- src/paginators/friends.paginator.v1.ts
- src/types/v1/user.v1.types.ts
- src/v1/client.v1.read.ts
Code to get the list of user objects of friends and followers of the specified user has been written.
Wrappers for the following endpoints have been written:
https://developer.twitter.com/en/docs/twitter-api/v1/accounts-and-users/follow-search-get-users/api-reference/get-friends-list
https://developer.twitter.com/en/docs/twitter-api/v1/accounts-and-users/follow-search-get-users/api-reference/get-followers-list
> feat: get friends/followers objects list V1

- src/types/v1/dm.v1.types.ts
- src/types/v1/entities.v1.types.ts
- src/v1/client.v1.ts
Fixes errors due to differences between MediaEntityV1 and the actual response type
When run as per [DownloadamediaattachedinaDM](https://github.com/PLhery/node-twitter-api-v2/blob/master/doc/v1.md#DownloadamediaattachedinaDM)
```js
const eventsPaginator = await client.v1.listDmEvents();
for await (const event of eventsPaginator) {
if (
event.type === EDirectMessageEventTypeV1.Create &&
event[EDirectMessageEventTypeV1.Create].message_data.attachment
) {
console.dir(event, { depth: null }); //log
const image = await client.v1.downloadDmImage(event);
}
}
```
The actual response of the event (DirectMessageCreateV1) was as follows.
```js
{
type: 'message_create',
id: '**********',
created_timestamp: '1668707634771',
message_create: {
target: { recipient_id: '**********' },
sender_id: …
```
> fix: ReceivedMessageCreateDataV1

- src/v2/client.v2.read.ts
- test/tweet.v2.test.ts
Issue: #430 
- Simplifies the logic of getting the query and options from the overload params, making it explicit when `query` is overridden and when it's not.
- Removes `Partial` from the type of `options` when it's the first parameter. The results in a type error when you provide a lone options object without a `query` key. For example: `client.v2.search({ max_results: 1 })` is a type error now. However, the type error is long and hard to read. I'll restate my suggestion from the issue of just reverting to the original API which was clearer, though that would be a breaking change now.
- Adds an additional test scenario for calling search with only an options object. This regrettably adds an additional 1.5 seconds to the runtime.
> Fix V2 search error with query key in options

- src/client/readonly.ts
the client setting (e.g. httpProxy) should also be configured using the same setting when create the basicClient to request token
> fix: Add missing client settings when create basicClient

- README.md
- doc/examples.md
- doc/rate-limiting.md
Thanks for the useful repository!!!
I think many users, including myself, would be on the free plan. Currently, users on the free plan do not have access to the v1 API endpoint. Therefore, in order to encourage more users to take advantage of this repository, I have rewritten the samples using v2.
In particular, the modification of `doc/examples.md` is important; simply rewriting v1 to v2 will not work. examples of working code is presented below (the former is used in this PR, but please let me know if you prefer the latter)
```
await client.v2.tweet({
text: 'My tweet text with two images!',
media: { media_ids: mediaIds }
});
```
```
await client.v2.tweet('My tweet text with two images!', 
{
media: { media_ids: mediaIds }
});
```
Note: Similar updates may be needed for functions other …
> [documentation] Rewrite the sample code using v2.tweet() instead of v1.tweet() because we unable to use v1.tweet() with free plan

- src/types/v2/tweet.v2.types.ts
- src/types/v2/user.v2.types.ts
https://devcommunity.x.com/t/announcing-connection-status-field-in-the-user-object-in-the-x-api-v2/212588
> feat: add connection_status user field

- src/types/v2/tweet.definition.v2.ts
- src/types/v2/tweet.v2.types.ts
extended `TweetV2` and `TTweetv2TweetField` to support `note_tweet`. 
API Docs: https://developer.twitter.com/en/docs/twitter-api/tweets/timelines/api-reference/get-users-id-tweets
> Type support for Tweets with more than 280 characters

- src/types/v2/spaces.v2.types.ts
Although not mentioned in the docs, the `state` attribute on a space can also be `canceled` (e.g. 1OdKrjgmNkeKX) and `ended` (once the space ends, e.g. 1dRJZEXDRQAGB; a recording may or may not be available but that's only returned by the unofficial periscope api, not the official spaces api).
> Add canceled and ended space state

- src/types/v2/tweet.definition.v2.ts
- src/types/v2/user.v2.types.ts
Issue #527: Added missing types: UserV2.public_metrics.like_count, and TweetV2.public_metrics.bookmark_count
> #527 - Added missing types to public_metrics

- src/types/v2/tweet.definition.v2.ts
Thanks for the useful repository!!
I am proposing this PR to address the following issues:
An error occurs when media_ids is an empty array `message: $.media.media_ids: there must be a minimum of 1 item in the array`.
An error occurs when media_ids is an array containing 5 or more items `message: $.media.media_ids: there must be a maximum of 4 items in the array`.
> Limit media_ids count from 1 to 4

- doc/v2.md
- src/types/v2/tweet.v2.types.ts
- src/v2/client.v2.read.ts
Create API for /usage in v2 API.
API
https://developer.x.com/en/docs/x-api/usage/tweets/introduction
API params (not listed in their official doc, but in their Postman workspace, also attached an easier to read version)
https://www.postman.com/xapidevelopers/twitter-s-public-workspace/request/o1gumn2/get-tweets-usage
https://code.peren.gouv.fr/hackathon-2024/retrieval-modules/platform-docs-versions/-/blob/main/X_Twitter-API-V2/Usage.md
> feat: get tweet usage v2

- src/types/entities.types.ts
- src/types/v2/tweet.definition.v2.ts
- src/types/v2/tweet.v2.types.ts
- src/types/v2/user.v2.types.ts
- Correct misnamed fields in `HashtagEntity` and `CashtagEntity` ([reference](https://developer.x.com/en/docs/x-api/data-dictionary/object-model/user)).
- Add `media_count` to `UserV2`, as it is included in the API response.
- Add `'edit_history_tweet_ids'` to `TTweetv2TweetField` ([reference](https://developer.x.com/en/docs/x-api/data-dictionary/object-model/tweet)).
- Add `media_key` to `TweetEntityUrlV2` ([reference](https://developer.x.com/en/docs/x-api/data-dictionary/object-model/tweet) - Sample Response).
> fix: add and correct field names

- src/types/v2/user.v2.types.ts
X API endpoints for:
- https://developer.x.com/en/docs/x-api/tweets/retweets/api-reference/get-tweets-id-retweeted_by
- https://developer.x.com/en/docs/x-api/tweets/likes/api-reference/get-tweets-id-liking_users
has `max_results` and `pagination_token` fields but they're not typed correctly in the implementation.
> fix: type definition for TweetRetweetedOrLikedByV2Params

- src/types/v2/tweet.definition.v2.ts
X api now supports community_id for post and lookup.
https://docs.x.com/x-api/posts/post-lookup-by-post-ids
https://docs.x.com/x-api/posts/creation-of-a-post
This adds type community_id to the payload.
> Add community id to tweet payload and response

- src/types/v2/community.v2.types.ts
- src/types/v2/index.ts
- src/v2/client.v2.read.ts
Added two new endpoints to v2 
- Search for Communities based on keywords.: https://docs.x.com/x-api/communities/search-communities
- Lookup for Community based on id: https://docs.x.com/x-api/communities/communities-lookup-by-community-id
> add community and searchCommunities endpoints

- src/v2/client.v2.write.ts
- Allows for a user to retrieve the `contentType` from a url (`www.some-url.com.image.png`), and upload media without using enum.
Previous PR got merged in quicker than what I was expecting.
> fix(upload-media): media type input type

- doc/v2.md
- src/types/v2/media.v2.types.ts
- src/v2/client.v2.write.ts
Added media metadata functionality from this endpoint https://docs.x.com/x-api/media/media-upload (only supports `alt_text` which I think is what people would want anyways) so we can migrate from the `v1` media endpoints as they're getting deprecated on March 31st
https://devcommunity.x.com/t/deprecating-the-v1-1-media-upload-endpoints/238196
Also updated the `v2` docs to include `uploadMedia` and the new `createMediaMetadata`
Related to https://github.com/PLhery/node-twitter-api-v2/issues/573 (missing metadata endpoint) and https://github.com/PLhery/node-twitter-api-v2/issues/569 (missing documentation)
> V2 Media Metadata & Updated V2 Docs

- src/v2/client.v2.write.ts
Issue was I was spreading the metadata params
Not working but should: `await client.v2.createMediaMetadata(mediaId, { alt_text: { text: 'Hello, world!' } });`
Working but shouldn't: `await client.v2.createMediaMetadata(mediaId, { metadata: {alt_text: { text: 'Hello, world!' } } });`
Issue was I had written based of our v1 metadata endpoint but the v1 doesn't take in `metadata` https://developer.x.com/en/docs/x-api/v1/media/upload-media/api-reference/post-media-metadata-create so updating to match the v2 https://docs.x.com/x-api/media/metadata-create
Reported here https://github.com/PLhery/node-twitter-api-v2/issues/579#issuecomment-2747647429
> Media V2 Metadata: don't spread metadata params

- src/types/v2/media.v2.types.ts
- src/v2/client.v2.write.ts
As announced [here](https://devcommunity.x.com/t/media-upload-endpoints-update-and-extended-migration-deadline/241818), within the next 1-2 weeks, the command query parameter used for chunked uploads will be deprecated for the POST https://api.x.com/2/media/upload endpoint.
They will replace the single POST https://api.x.com/2/media/upload endpoint (previously using a commands query parameter with INIT, APPEND, and FINALIZE) with dedicated endpoints for each command:
- POST [https://api.x.com/2/media/upload/initialize](https://docs.x.com/x-api/media/media-upload-initialize)
- POST [https://api.x.com/2/media/upload/{id}/append](https://api.x.com/2/media/upload/:media_id/append)
- POST [https://api.x.com/2/media/upload/{id}/finalize](https://api.x.com/2/media/upload/:media_id/finalize)
In …
> Adapt uploadMedia to new endpoints for chunked media upload in V2

- src/client-mixins/request-handler.helper.ts
- src/types/v2/media.v2.types.ts
- src/v2/client.v2.write.ts
Fixes error handling using the `uploadMedia` function and rollbacks `segment_index` to start from zero instead of from one.
> Fix error handling and use segment_index starting from zero

- src/types/v2/tweet.v2.types.ts
This PR adds 'article' to the `TTweetv2TweetField` type definition. The article field is a valid parameter for tweet.fields as documented in the X API documentation for [Full Archive Search](https://docs.x.com/x-api/posts/full-archive-search) and [Recent Search](https://docs.x.com/x-api/posts/recent-search).
This change enables users of the library to request article content in tweets, particularly useful for tweets that contain Notes.
- Added 'article' to the `TTweetv2TweetField` type union in `src/types/v2/tweet.v2.types.ts`
This change is:
- Backward compatible
- Purely additive
- Has no runtime impact
- Enhances type safety
- [X API Full Archive Search Documentation](https://docs.x.com/x-api/posts/full-archive-search)
- [X API Recent Search …
> chore: add article as enum

- src/types/v2/tweet.definition.v2.ts
When posting to communities, this makes the post to be shared with followers and show up on the timeline too.
https://docs.x.com/x-api/posts/create-post#body-share-with-followers
> Add share_with_followers in SendTweetV2Params

- doc/helpers.md
- src/helpers.ts
- test/helpers.test.ts
- Ensure `trimUndefinedProperties` only iterates own keys to avoid touching prototype chain
- Document `trimUndefinedProperties` behavior and add example
- Add unit test confirming prototype properties are untouched
- `npm run mocha test/helpers.test.ts`
> Avoid iterating prototype properties in trimUndefinedProperties

- doc/v2.md
written by Codex
- document the v2 communities endpoints
> docs: add communities endpoints to v2 docs

- README.md
- doc/ads.md
- doc/v2.md
Written by codex
- add initial Twitter Ads API beta documentation and link in README
- correct `image.png` example in v2 upload media docs
> docs: add ads API docs and fix typo

- doc/v2.md
- src/types/v2/community.v2.types.ts
- src/v2/client.v2.read.ts
Written by codex
- document available `usage.fields` values and note that Tweet usage is app-only
- include an example of retrieving `project_usage` and `project_cap`
> docs: clarify usage endpoint

- doc/streaming.md
- src/types/v2/streaming.v2.types.ts
- allow using `delete_all` query to remove all stream rules
- document how to delete all rules using `updateStreamRules`
> feat(stream): support delete_all query for stream rules

- doc/rate-limiting.md
- src/client-mixins/request-handler.helper.ts
- src/types/responses.types.ts
- test/rate-limit.test.ts
- expose `x-user-limit-24hour-*` headers on responses via `rateLimit.userDay`
- document optional daily application and user limits
- add unit test for daily rate limit parsing
- `npm run mocha test/rate-limit.test.ts`
- `npm run lint`
Fixes #553
> Parse user 24h rate limit headers

- doc/streaming.md
- src/types/v2/streaming.v2.types.ts
Created by Codex
- allow passing `pagination_token` and `max_results` to `v2.streamRules`
- expose pagination metadata in `StreamingV2GetRulesResult`
- document how to paginate stream rules and limit results per page
Fixes #537
> feat: support stream rule pagination
