PLhery/node-twitter-api-v2

.github/workflows/CI.yml, README.md, doc/examples.md, package.json, src/client-mixins/request-maker.mixin.ts, src/types/errors.types.ts, src/types/v2/shared.v2.types.ts, src/types/v2/tweet.definition.v2.ts, test/media-upload.test.ts, test/stream.test.ts, test/tweet.v1.test.ts, test/tweet.v2.test.ts, test/user.v2.test.ts
Some small README improvements to review and add error enumerations (for both v1 & v2).
Error parsing improvements (error messages with error code (v1)/error link (v2)).
=> README & error parsing improvements

doc/v2.md, src/test/utils.ts, src/types/v2/tweet.v2.types.ts, src/v2/client.v2.write.ts, test/tweet.v2.test.ts
Self descriptive :) 
Quite a short feature!
=> feature(likes/v2): Add like/unlike for v2 API

src/stream/TweetStream.ts
=> Fixed ETwitterStreamEvent.DataKeepAlive not being emitted

doc/basics.md
Update the doc/basics.md to include rate limiting explanations and examples (https://github.com/PLhery/node-twitter-api-v2/issues/32)
=> Update documentation with rate limit basics

doc/examples.md, doc/streaming.md, doc/v1.md, doc/v2.md, src/types/v1/dm.v1.types.ts
- Update examples with real-life usages :) 
- Add TOCs for big v1/v2 comprehensive endpoint lists
- Fix type error in send DM attachment type union
=> Update examples in doc & fix type errors

doc/auth.md, doc/basics.md
Since a bit later it is mentioned that steps 1 & 2, so it causes confusion which steps 1 & 2 so I made it an ordered list instead of an unordered one :)
=> Use ol instead of ul

README.md, changelog.md, doc/auth.md, doc/basics.md, doc/examples.md, doc/streaming.md, src/client-mixins/oauth2.helper.ts, src/client-mixins/request-maker.mixin.ts, src/client.base.ts, src/client/readonly.ts, src/types/auth.types.ts, src/types/client.types.ts, src/types/errors.types.ts, src/v2/client.v2.read.ts, src/v2/client.v2.write.ts, test/auth.test.ts, test/list.v1.test.ts
- Add full-featured OAuth2 user context, with typed scopes.
- Add `users/me` v2 endpoint
LInked to #125.
=> Feat: Add OAuth2 user context 

src/v2/client.v2.read.ts
=> Fix list lookup HTTP method

changelog.md, doc/auth.md, doc/errors.md, doc/examples.md, doc/helpers.md, doc/paginators.md, doc/v2.md, src/client-mixins/oauth2.helper.ts, src/client-mixins/request-handler.helper.ts, src/index.ts, src/paginators/TwitterPaginator.ts, src/paginators/tweet.paginator.v2.ts, src/paginators/v2.paginator.ts, src/settings.ts, src/types/v2/tweet.v2.types.ts, src/v2/includes.v2.helper.ts, test/list.v1.test.ts
- Feat: Helpers for v2 includes
- Feat: Support for custom debug loggers
- Fix: Errors accessor to get API errors in paginators #145
- Fix: Correctly update .includes/.meta/.errors in paginators when using async iterator #142
- Doc: Many doc & examples improvements
=> Feat: 1.9: Fix paginator includes update, include helpers

README.md
- Makes a small change to the readme 😄.
=> chore: updates readme semantics

src/paginators/tweet.paginator.v2.ts, src/types/v2/tweet.v2.types.ts
=> fix: Use next_token instead of until_id if pagination token available

doc/rate-limiting.md
The sleep function had parameters which were incorrectly sent to setTimeout. Fixed it.
=> Update sleep function

doc/basics.md, src/client-mixins/request-handler.helper.ts, src/client-mixins/request-maker.mixin.ts, src/client.base.ts, src/client.subclient.ts, src/client/readonly.ts, src/types/client.types.ts
Add support of custom HTTP agents. Correctly support timeout function of native `http` package.
Addresses #149.
=> feat: Support custom HTTP agents

doc/errors.md, src/client-mixins/request-handler.helper.ts, src/client-mixins/request-maker.mixin.ts, src/types/client.types.ts, src/types/request-maker.mixin.types.ts
Let user decide the compression option selected by the lib during requests.
=> feat: Precise compression option

doc/auth.md
Changed "remplace" to "replace"
=> Updated auth.md spelling

doc/auth.md
=> Updated auth.md documentation spelling in code example comment

src/types/v2/tweet.v2.types.ts
Fixes PLhery/node-twitter-api-v2#236
=> fix: add sort_order to v2 search params

doc/v1.md
Just some spelling corrections
=> doc: fix typo

src/types/v1/tweet.v1.types.ts, src/v1/client.v1.write.ts
Fixes PLhery/node-twitter-api-v2#243
=> fix: better error message for failed upload

src/types/v1/entities.v1.types.ts
It's not documented in the [Twitter API specs](https://developer.twitter.com/en/docs/twitter-api/v1/data-dictionary/object-model/extended-entities) but the tweets I'm pulling (v1) show this field.
Let me know if I missed something, didn't see any contributing docs
Example tweet ID: 1525009900157276161 (https://twitter.com/Otter_Uchan/status/1525009900157276161)
v1 response:
```json
{
...
"extended_entities": {
"media": [
{
"additional_media_info": {
"monetizable": false
},
"display_url": "pic.twitter.com/JbXOn2BoMJ",
"expanded_url": "https://twitter.com/Otter_Uchan/status/1525009900157276161/video/1",
"id": 1525009839293796400,
"id_str": "1525009839293796352",
"indices": [13, 36],
"media_url": "http://pbs.twimg.com/ext_tw_video_thumb/1525009839293796352/pu/img/rj-_qOgK1SfR4zba.jpg", …
```
=> fix(MediaVideoInfoV1): Add duration_millis property

src/types/v1/entities.v1.types.ts
properties 'source_user_id' and 'source_user_id_str' are missing, for example
```json
{
"created_at": "Thu Jun 09 00:11:11 +0000 2022",
"id": 1534689530334392300,
"id_str": "1534689530334392320",
"full_text": "(Personal trainer.)https://t.co/pJhQk8l4UC",
"truncated": false,
"display_text_range": [
0,
42
],
"entities": {
"hashtags": [],
"symbols": [],
"user_mentions": [],
"urls": [],
"media": [
{
"id": 1534184954586087400,
"id_str": "1534184954586087424",
"indices": [
19,
42
],
"media_url": "http://pbs.twimg.com/ext_tw_video_thumb/1534184954586087424/pu/img/S9XXYQee85AGtPG5.jpg",
"media_url_https": "https://pbs.twimg.com/ext_tw_video_thumb/1534184954586087424/pu/img/S9XXYQee85AGtPG5.jpg",
"url": "https://t.co/pJhQk8l4UC",
"display_url": "pic.twitter.com/pJhQk8l4UC",
"expanded_url": …
```
=> add missing properties 'source_user_id' and 'source_user_id_str' in MediaEntityV1

doc/examples.md
=> Correct spelling

README.md
To make the example more readable.
=> Unminify 'roClient'

package.json, tsconfig.cjs.json, tsconfig.esm.json, tsconfig.json
Hi, I would like to use this package for ESNext.
I have prepared new tsconfig.json and now `npm run build` generates commonjs and esmodule JS files
=> chore: 🤖 dual package for esnext and commonjs

changelog.md, doc/auth.md, doc/basics.md, doc/errors.md, doc/examples.md, doc/helpers.md, doc/plugins.md, doc/streaming.md, doc/v1.md, doc/v2.md, src/client-mixins/oauth1.helper.ts, src/client/readonly.ts, src/paginators/TwitterPaginator.ts, src/paginators/tweet.paginator.v1.ts, src/stream/TweetStream.ts, src/types/errors.types.ts, src/types/v1/dm.v1.types.ts, src/types/v1/tweet.v1.types.ts, src/v2/client.v2.write.ts, test/plugin.test.ts, test/stream.test.ts
There were a lot of typos and nearly all markdown links did not work.
=> chore: fix typos and markdown links

package.json, src/v1/client.v1.write.ts
Adding a returnFullMediaData parameter per: https://github.com/PLhery/node-twitter-api-v2/issues/506
=> Added returnFullMediaData parameter to v1 uploadMedia

doc/v2.md, src/v2/client.v2.write.ts
The API implementation is already the right one only need to update the docs and we're good
=> improve docs

README.md, doc/basics.md, doc/examples.md, doc/http-wrappers.md, doc/streaming.md, doc/v1.md, package.json, src/client-mixins/request-handler.helper.ts, src/client-mixins/request-param.helper.ts, src/client/readonly.ts, src/globals.ts, src/types/errors.types.ts, src/types/v1/streaming.v1.types.ts, src/v1/client.v1.read.ts, src/v1/client.v1.ts, src/v1/client.v1.write.ts, src/v2/client.v2.read.ts, src/v2/client.v2.write.ts, test/tweet.v1.test.ts, test/tweet.v2.test.ts
This PR is based on Elon's tweet: https://x.com/elonmusk/status/1791351500217754008
Please help review @PLhery
=> update domain from twitter.com to x.com

src/types/v2/tweet.v2.types.ts, src/types/v2/user.v2.types.ts
I added "most_recent_tweet_id" type to TTweetv2UserField and UserV2.
=> feat: add most_recent_tweet_id

doc/basics.md
=> Updated basics.md typo

README.md, src/ads-sandbox/client.ads-sandbox.read.ts, src/ads-sandbox/client.ads-sandbox.ts, src/ads-sandbox/client.ads-sandbox.write.ts, src/ads/client.ads.read.ts, src/ads/client.ads.ts, src/ads/client.ads.write.ts, src/client/index.ts, src/globals.ts
Adding clients for Twitter Ads in the manner of already existing lab client.
=> Add clients for X  Ads and Ads Sandbox

src/types/v2/tweet.v2.types.ts, src/types/v2/user.v2.types.ts
Missed "profile_banner_url" declaration in user.field for some reason =)
=> fix: absence of profile_banner_url field

doc/v1.md, doc/v2.md
- document `.hideReply()` and `.quote()` in v2 docs
- add `.quote()` docs for v1
=> docs: document quote and hide reply features

src/types/v2/user.v2.types.ts
- expose new X API user fields including affiliation, subscription details, identity verification and more
=> feat: add new user fields
